build: okameron
	gcc --std=c90 --debug -O3 okas.c -o okas
	gcc -O3 okrotool.c -o okrotool
	gcc --debug -O0 fennecfstool.c -lm -o fennecfstool

okameron:
	git clone https://github.com/TalonFox/okameron